## **Introduction to NumPy:**
NumPy is a powerful library that provides support for arrays, matrices, and mathematical functions, making it a core tool in scientific computing and data analysis.
NumPy is a fundamental library in Python for numerical computations and data manipulation. It provides support for arrays and matrices, along with a wide range of mathematical functions to operate on these arrays efficiently. This makes it an essential tool for scientific computing and data analysis tasks.

### **Some of the differences betweeen NumPy_Array and Python_List**
NumPy arrays and Python Lists are both used to store collections of data, but theyy have several key differences in terms of perforamnce, functionality, and memory management.
- Homogeneity
- Performance
- Memory Efficiency
- Size and Shape


### **Difference between NumPy and List in Code**

In [2]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# Adding 2 to a Python List
python_list = [1,3,5,7,9]
python_list_with_2 = [x + 2 for x in python_list]
print("Python List with 2 added:", python_list_with_2)

# Adding 2 to a NumPy array
import numpy as np

numpy_array = np.array([1,3,5,7,9])
numpy_array_with_2 = numpy_array + 2
print("NumPy Array with 2 added:", numpy_array_with_2)


Python List with 2 added: [3, 5, 7, 9, 11]
NumPy Array with 2 added: [ 3  5  7  9 11]


In [8]:
for x in python_list:
    x + 2
print("Python List with 2 added:", python_list_with_2)

Python List with 2 added: [3, 5, 7, 9, 11]


In [9]:
x = list(map(lambda x:x+2, python_list))
x 

[3, 5, 7, 9, 11]

### **Performance**

In [10]:
import time
# Create large arrays
python_list = list(range(10**6))
numpy_array = np.array(range(10**6))

# Measure the time taken for element 
start_time = time.time()
python_list_sum = [x + 2 for x in python_list]
end_time = time.time()
print(f"Time taken for Python list addition: {end_time - start_time} seconds")

# Measure the time takes for element-wise addtion using NumPy array
start_time = time.time()
numpy_array_sum = numpy_array + 2
end_time = time.time()
print(f"Time taken for NumPy array addition: {end_time - start_time} seconds")

Time taken for Python list addition: 0.09040641784667969 seconds
Time taken for NumPy array addition: 0.005013227462768555 seconds


### **Memory**

In [11]:
import sys

# Create a Python List and a NumPy array with the same data
python_list = list(range(10**6))
numpy_array = np.array(range(10**6))

# Check the size of each object in bytes
size_python_list = sys.getsizeof(python_list)
size_numpy_array = numpy_array.nbytes

print(f"Size of Python list: {size_python_list} bytes")
print(f"Size of NumPy array: {size_numpy_array} bytes")

Size of Python list: 8000056 bytes
Size of NumPy array: 8000000 bytes


### **Installing and Importing NumPy:**

In [12]:
# To import NumPy in your Python script or notebook:
import numpy as np 

### **NumPy arange and linspace**

In [13]:
arr1 = np.arange(0, 10, 2)
arr1

array([0, 2, 4, 6, 8])

In [14]:
arr2 = np.linspace(0, 10, num=6)   # Creates array; [0., 2.5, 5., 7.5, 10.]
arr2

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [15]:
x = np.linspace(0, 20, 10, endpoint=False, dtype = 'int')
x 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### **Types of NumPy Array**
### **Numpy 1D Array**
### **NumPy-Create 1D Array**
- One dimensional array consists elements only in one dimension. In other words, the shape of the numpy array should contain only one value in the tuple.
- To create a one dimensional array in numpy, you can use eithe of the numpy.array(), numpy.arange(), or numpy.linspace() functions based on the choice of initialisation.

In [17]:
arr3 = np.array([5, 8, 12])
print(arr3)

[ 5  8 12]


In [18]:
arr4 = np.arange(5, 14, 2)
print(arr4)

[ 5  7  9 11 13]


#### **NumPy 2D Array**

In [20]:
# Create a 2D array with shape (3, 4)
arr5 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])   # np.array
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
# Create a 2D array with shape (3, 2)
arr6 = np.zeros((3,2), dtype = int)
print(arr6)

[[0 0]
 [0 0]
 [0 0]]


In [23]:
# Create a 2D array with shape (3, 4)
shape = (3, 4)
arr7 = np.ones(shape, dtype = int)
print(arr7)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [24]:
# Create a 2D array with shape (4, 3)
arr8 = np.empty((4, 3), dtype = int)
print(arr8)

[[206158430258 223338299442 206158430253]
 [193273528377 236223201329 206158430292]
 [249108103223 231928234036 210453397562]
 [197568495666 240518168626 386547056695]]


### **NumPy 3D Array**
#### **Create a 3D Array using numpy.array()**
- Pass a nested list (list of lists of lists) to numpy.array() function.
- In the follwing program, we create a numpy 3D array of shape (2,3,4).

In [25]:
# Create a 3D array with shape (2, 3, 4)
nested_list = [[[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16], [17,18,19,20], [21,22,23,24]]]
arr9 = np.array(nested_list)
print(arr9)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [26]:
# Create a 3D array with shape (2, 3, 4)
shape = (2, 3, 4)
arr11 = np.zeros(shape)
print(arr11)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [27]:
# Create a 3D array with shape (3, 2, 3)
shape = (3, 2, 3)
arr12 = np.ones(shape)
print(arr12)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [30]:
shape = (2, 2, 2)
arr12 = np.empty(shape)
print(arr12)

[[[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 1.14227977e-320]
  [3.11525958e-307 1.24610723e-306]]]


### **numpy.random module:**
- This module provides a suite of functions for generating random numbers.

### **numpy.random.rand:**
- This function generates random numbers from a uniform distribution over [0,1]. It takes dimensions as input and returns an array of the specified shape.

In [31]:
random_numbers = np.random.rand(3,3)   # Generates a 3x3 array of random numbers between 0 and 1
random_numbers

array([[0.18271674, 0.96895315, 0.73152372],
       [0.14279597, 0.69667802, 0.61066304],
       [0.60443477, 0.81920347, 0.54598817]])

### **numpy.random.randn:**
- This function generates random numbers from a standard normal distribution (mean=0, standard deviation=1). It also takes dimensions as input and returns an array of the specified shape.

In [32]:
random_numbers = np.random.randn(2,2)  # Generates a 2x2 array of random numbers from a standard normal distribution 
random_numbers

array([[-1.69771314, -0.43878316],
       [ 0.40106722, -0.83297179]])

### **numpy.random.randint:**
- This function generates random integers from a specified low (inclusive) to high (exclusive) range. It can take additional parameters to specify the size and shape of the output array.

In [4]:
random_numbers = np.random.randint(1, 10, size=(4, 3)) #Generates a 4x3 array of random integers between 1(inclusive) & 10(exclusive)
random_numbers

array([[9, 6, 2],
       [4, 7, 7],
       [9, 1, 3],
       [2, 6, 2]], dtype=int32)

### **Creating NumPy Array**

In [5]:
ab = np.array([2,4,6,8,12,16,20])
ab

array([ 2,  4,  6,  8, 12, 16, 20])

In [6]:
ac = np.array([1,0.1,2,0.2,3,0.3])
ac

array([1. , 0.1, 2. , 0.2, 3. , 0.3])

In [7]:
c = np.array([2.01, 2.02, 2.03])
c

array([2.01, 2.02, 2.03])

In [11]:
b = [1,3,5,7,9,11]
for i in b:
    print(f"{i} = {type(i)}")

1 = <class 'int'>
3 = <class 'int'>
5 = <class 'int'>
7 = <class 'int'>
9 = <class 'int'>
11 = <class 'int'>


In [10]:
type(ac)   # to find the type

numpy.ndarray

In [12]:
np.arange(2,8, dtype = float)

array([2., 3., 4., 5., 6., 7.])

In [13]:
i = np.identity(3)  # Identity matrix is a matrix where the diagonal elements will be 1 and other elements will be 0.
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
j = np.diag([2,4,6])  # Diagonal matrix is a matrix where the diagonal elements are different and other elements are 0.
j

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [16]:
a = np.arange(9).reshape(3,3)
a 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
x = np.array([1,2,3])    # Copying the numpy into another variable
y = x
z = np.copy(x)
x,y,z

(array([1, 2, 3]), array([1, 2, 3]), array([1, 2, 3]))

In [18]:
np.linspace(2.0, 3.0, num = 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [19]:
np.linspace(2.0, 3.0, num = 5, endpoint = False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [25]:
specific = np.full((3,3), 2)
specific

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [26]:
ones = np.ones((2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
zeros = np.zeros((4,2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### **Changing the type of the data type**

In [28]:
cd = np.array([11,22,33], dtype = float)
cd

array([11., 22., 33.])

In [29]:
db = np.array([11,22,33], dtype = complex)
db

array([11.+0.j, 22.+0.j, 33.+0.j])

In [30]:
db.astype(int)

C:\Users\91938\AppData\Local\Temp\ipykernel_13060\1171016635.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  db.astype(int)


array([11, 22, 33])

In [31]:
np.array([121, 224, 326], dtype = np.int64)   # numpy.arange creates arrays with regularly incrementing values. Check the documentation for complete information and examples.

array([121, 224, 326])

#### **Reshape**
- Both of number products should be equal to number of items present inside the array.

In [32]:
re = np.arange(1,11). reshape(2,5)
re


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
re1 = np.arange(1,21).reshape(2,2,5)
re1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [35]:
re1 = np.arange(1,11).reshape(2,5)
re2 = np.arange(1,13).reshape(3,4)
re2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### **Shape**
- Gives each item consists of number of rows and number of columns.

In [36]:
re = np.arange(1,11).reshape(5,2)
re.shape

(5, 2)

In [40]:
arr = np.array(([1,2,3], [4,5,6]))
arr2 = np.array([5,6,7])
arr2.shape

(3,)

#### **Size**
- Gives number of elements or items

In [44]:
re = np.arange(1,11).reshape(5,2)
re.size 

10

In [49]:
re = np.arange(1,16).reshape(3,5)
re.size

15

#### **ItemSize**
- Memory occupied by the item.

In [50]:
re1 = np.arange(1,13).reshape(3,4)
re1.itemsize

8

#### **Array Operations:**
- Numpy supports element wise operations on arrays. Basic arithmetic operations like addition, subtraction, multiplication and division are performed element wise.

#### **Scalar Operations**
- It includes performing addition, subtraction or multiplication on each element of a Numpy array.

In [53]:
z = np.arange(12).reshape(3,4)
z1 = np.arange(12,24).reshape(3,4)
z1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
z + 2 

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [55]:
arr_1D = np.array([1,2,3,4,5])
re_add = arr_1D + 2
re_sub = arr_1D - 2
re_mul = arr_1D * 2
re_div = arr_1D / 2
re_add, re_sub, re_mul, re_div

(array([3, 4, 5, 6, 7]),
 array([-1,  0,  1,  2,  3]),
 array([ 2,  4,  6,  8, 10]),
 array([0.5, 1. , 1.5, 2. , 2.5]))

#### **Relational Operations**
- The relational operations are also known as comparision operations, their main function is to return either true or false based on the value of operands.

In [56]:
z2 = np.arange(12,24).reshape(3,4)
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
z2>20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [58]:
x = [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
for i in x:
    if i > 20:
        print(i)

21
22
23
24
25


In [59]:
z2[z2>20]

array([21, 22, 23])

In [62]:
arr1 = np.array([-1, 4, 12])
arr2 = np.array([2, 6, 10])

comp = arr1 > arr2
comp

array([False, False,  True])

In [63]:
arr1 = np.array([True, False, True, False])
arr2 = np.array([False, True, True, False])

_and = np.logical_and(arr1, arr2)
_or = np.logical_or(arr1, arr2)
_and, _or

(array([False, False,  True, False]), array([ True,  True,  True, False]))

#### **Vector Operations**
- We can apply on both numpy arrays

In [65]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

addition, subtraction, multiplication,  division

(array([5, 7, 9]),
 array([-3, -3, -3]),
 array([ 4, 10, 18]),
 array([0.25, 0.4 , 0.5 ]))

In [66]:
p = np.arange(12).reshape(4, 3)
q = np.arange(12).reshape(4, 3)

addition = p + q
addition
 

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

#### **Array Functions**

In [3]:
b1 = np.random.random((3,3))
b1

array([[0.14469459, 0.3214268 , 0.62275014],
       [0.56028421, 0.59619573, 0.11689501],
       [0.55260858, 0.41431606, 0.07579571]])

In [5]:
b2 = np.round(b1*100)
b2.astype('int')

array([[14, 32, 62],
       [56, 60, 12],
       [55, 41,  8]])

In [9]:
x = np.max(b2)
x

np.float64(62.0)

In [10]:
x = np.max(b2, axis = 1)   # max of every row
x

array([62., 60., 55.])

In [17]:
y = np.min(b2)
print(y)

8.0


In [13]:
y = np.min(b2, axis = 1)
y

array([14., 12.,  8.])

In [18]:
z = np.average(b2)
print(z)

37.77777777777778


In [19]:
c = np.median(b2)
print(c)

41.0


In [20]:
d = np.prod(b2, axis = 1)    # Product of every row
print(d)

[27776. 40320. 18040.]


In [21]:
s = np.sum(b2)
print(s)

340.0


In [22]:
v = np.var(b2)
print(v)

429.9506172839506


In [24]:
s1 = np.sum(b2, axis = 0)     # Sum of every column
print(s1)

[125. 133.  82.]


#### **Trignometric Functions**

In [36]:
a = np.arange(1, 16).reshape(3,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [37]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [38]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [39]:
np.tan(a)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [47]:
x = np.sin(a)
y = np.cos(a)
z = np.tan(a)
d = 1/x
print(d)

[[ 1.18839511  1.09975017  7.0861674  -1.32134871 -1.04283521]
 [-3.57889955  1.52210106  1.01075622  2.42648664 -1.83816396]
 [-1.00000979 -1.8636796   2.38000584  1.0094817   1.53778056]]


#### **Logarithm and Exponential**

In [42]:
np.log(100)

np.float64(4.605170185988092)

In [43]:
np.exp(10)

np.float64(22026.465794806718)

In [44]:
np.sqrt(49)

np.float64(7.0)

In [45]:
np.power(3, 5)

np.int64(243)

In [48]:
arr = np.array([10,20,30,40,50])
sqrt_result = np.sqrt(arr)
print(sqrt_result)

exp_result = np.exp(arr)

sin_result = np.sin(arr)
cos_result = np.cos(arr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


#### **Round Function**
The numpy.round() function rounds the elements of an array to the nearest integer or to the specified number of decimals.

In [49]:
#Round to the nearest integer
arr = np.array([1.2, 3.8, 4.6, 2.1, 5.4])
rounded_arr = np.round(arr)
print(rounded_arr)

[1. 4. 5. 2. 5.]


In [51]:
#Round to two decimals
arr = np.array([1.234, 6.731, 8.782, 3.451])
rounded_arr = np.round(arr, decimals=2)
print(rounded_arr)

[1.23 6.73 8.78 3.45]


#### **Floor Function**
The numpy.floor() function returns the largest integer less than or equal to each element of an array.

In [52]:
# Floor operation
arr = np.array([1.2, 2.7, 3.5, 4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [54]:
np.floor(np.random.random((2,3))*100)   # Gives the smallest integer

array([[60., 82., 98.],
       [ 6., 71., 51.]])

#### **Ceil Function**
The numpy.ceil() function returns the smallest integer greater than or equal to each element of an array.

In [55]:
arr = np.array([1.2, 2.7, 3.5, 4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [56]:
np.ceil(np.random.random((2,3))*100)  ## Gives highest integer

array([[ 9., 40., 13.],
       [29., 95., 39.]])

#### **Set Functions**
- 'np.union1d'
- 'np.intersect1d'
- 'np.setdiff1d'

In [2]:
i = np.array([1,2,3,4,5])
j = np.array([3,4,5,6,7])

In [5]:
np.union1d(i,j)

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
np.intersect1d(i,j)

array([3, 4, 5])

In [8]:
# Set difference
np.setdiff1d(i,j)

array([1, 2])

#### **Indexing and Slicing:**
The user can access and modify elements of arrays using indexing and slicing. Indexing starts at 0, and slicing allows the user to extract portions of arrays.

In [10]:
arr = np.array([10,20,30,40,50])
first_element = arr[0]
sub_array = arr[1:4]
a = arr[-1]
first_element, sub_array, a

(np.int64(10), array([20, 30, 40]), np.int64(50))

In [11]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [12]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a2[1,2]

np.int64(6)

In [14]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a2[0,1]

np.int64(1)

In [17]:
print(a3[1,0,1])
print(a3[1,1,0])
print(a3[0,0,1])

5
6
1


In [18]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a1[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a2[0:1,1:]

array([[1, 2, 3]])

In [21]:
a2[0, :]   # Fetching total first row

array([0, 1, 2, 3])

In [22]:
a2[:, 2]    # Fetching total third column

array([ 2,  6, 10])

In [23]:
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [26]:
a3[1]

array([[4, 5],
       [6, 7]])

In [27]:
a3[0,1,:]

array([2, 3])

In [28]:
a3[1,:,1]

array([5, 7])

#### **isin**
We can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [37]:
a = np.array([10,20,30,110])
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a, items)

array([ True,  True,  True, False])

In [38]:
a[np.isin(a, items)]

array([10, 20, 30])

In [39]:
np.isin(10, items)

array(True)

In [40]:
# Create a 2D array 
arr = np.array([[1,3,5],
                [8,2,4]])

# Find the index of the maximum value in the entire array
max_index = np.argmax(arr)
print("Index of maximum value:", max_index)

# Find the indices of the maximum values along each column
max_indices_col = np.argmax(arr, axis = 0)
print("Indices of maximum values along each column:", max_indices_col)

Index of maximum value: 3
Indices of maximum values along each column: [1 0 0]


In [42]:
# Create a 2D array
arr == np.array([[1,3,5],
                 [8,2,4]])

# Find the index of the minimum value in the entire array
min_index = np.argmin(arr)
print("Index of minimum value:", min_index)

# Find the indices of the minimum values along each row
min_indices_row = np.argmin(arr, axis = 1)
print("Indices of minimum values along each row:", min_indices_row)

Index of minimum value: 0
Indices of minimum values along each row: [0 1]


#### **Array Methods**
#### **np.where**
- The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [48]:
a = np.arange(1,101)
print(a)
np.where(a>50)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)

In [49]:
# Replace all elements > 50 with 0
np.where(a>50,0,a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

#### **Iterating**

In [50]:
a1 = np.arange(10)

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [51]:
a2 = np.arange(12).reshape(3,4)

# Looping on 2D array
for i in a2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [52]:
a3 = np.arange(8).reshape(2,2,2)

# Looping on a 3D array
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [53]:
for i in a3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7


In [54]:
for i in np.nditer(a2):
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [55]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


In [56]:
a4 = np.arange(12,24).reshape(3,4)
a4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
for i in np.nditer(a4):
    if i % 2 == 0:
        print(i)

12
14
16
18
20
22


In [58]:
for i in np.nditer(a4):
    if i % 2 != 0:
        print(i)

13
15
17
19
21
23


#### **Sorting**

In [66]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)
a , b

(array([52, 45, 37,  1, 34, 72, 76,  8, 73, 16, 59, 19, 66, 76, 49],
       dtype=int32),
 array([[30, 35, 67, 60],
        [ 2,  9, 69, 18],
        [20, 43, 30, 75],
        [56, 13,  3, 72],
        [56, 31, 44, 12],
        [54, 96, 82, 54]], dtype=int32))

In [67]:
np.sort(a)

array([ 1,  8, 16, 19, 34, 37, 45, 49, 52, 59, 66, 72, 73, 76, 76],
      dtype=int32)

In [68]:
np.sort(a)[::-1]  # Descending order

array([76, 76, 73, 72, 66, 59, 52, 49, 45, 37, 34, 19, 16,  8,  1],
      dtype=int32)

In [69]:
np.sort(b)

array([[30, 35, 60, 67],
       [ 2,  9, 18, 69],
       [20, 30, 43, 75],
       [ 3, 13, 56, 72],
       [12, 31, 44, 56],
       [54, 54, 82, 96]], dtype=int32)

In [70]:
np.sort(b, axis = 0)    # Column wise sorting

array([[ 2,  9,  3, 12],
       [20, 13, 30, 18],
       [30, 31, 44, 54],
       [54, 35, 67, 60],
       [56, 43, 69, 72],
       [56, 96, 82, 75]], dtype=int32)

#### **Append**

In [72]:
b

array([[30, 35, 67, 60],
       [ 2,  9, 69, 18],
       [20, 43, 30, 75],
       [56, 13,  3, 72],
       [56, 31, 44, 12],
       [54, 96, 82, 54]], dtype=int32)

In [73]:
b.shape[0]

6

In [71]:
np.append(b, 1)

array([30, 35, 67, 60,  2,  9, 69, 18, 20, 43, 30, 75, 56, 13,  3, 72, 56,
       31, 44, 12, 54, 96, 82, 54,  1])

In [76]:
np.ones((6, 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [75]:
# Adding one row to 2D array
np.append(b, np.ones((b.shape[0], 1))).astype('int')

array([30, 35, 67, 60,  2,  9, 69, 18, 20, 43, 30, 75, 56, 13,  3, 72, 56,
       31, 44, 12, 54, 96, 82, 54,  1,  1,  1,  1,  1,  1])

In [77]:
# Adding new column
np.append(b, np.random.random((6,1)),axis = 1)

array([[30.        , 35.        , 67.        , 60.        ,  0.35657564],
       [ 2.        ,  9.        , 69.        , 18.        ,  0.80834267],
       [20.        , 43.        , 30.        , 75.        ,  0.92582634],
       [56.        , 13.        ,  3.        , 72.        ,  0.2246225 ],
       [56.        , 31.        , 44.        , 12.        ,  0.39825264],
       [54.        , 96.        , 82.        , 54.        ,  0.22878271]])

#### **np.unique**

In [78]:
x = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [79]:
np.unique(x)

array([1, 2, 3, 4, 5, 6])

#### **Dot Product**

In [80]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [81]:
c = np.dot(a,b)
c

array([[19, 22],
       [43, 50]])

In [82]:
A = np.array([[11,12], [13,14]])
B = np.array([[15,16], [17,18]])
dot_product = np.dot(A, B)
dot_product

array([[369, 392],
       [433, 460]])

#### **Percentile**
- numpy.percentile() function used to compute the nth percentile of the given data(array elements) along the specified axis.

In [2]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)

In [5]:
np.sort(a)

array([19, 21, 29, 33, 36, 44, 53, 71, 75, 83, 85, 88, 89, 93, 95],
      dtype=int32)

In [6]:
np.percentile(a,100)  # max

np.float64(95.0)

In [7]:
np.percentile(a,50)   # median

np.float64(71.0)

In [8]:
np.percentile(a,0)   # min

np.float64(19.0)

In [9]:
np.percentile(a,25)

np.float64(34.5)

In [10]:
np.percentile(a,75)

np.float64(86.5)

#### **Flip**
- The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [11]:
a

array([75, 53, 36, 33, 44, 21, 88, 95, 19, 93, 83, 85, 71, 89, 29],
      dtype=int32)

In [12]:
np.flip(a)

array([29, 89, 71, 85, 83, 93, 19, 95, 88, 21, 44, 33, 36, 53, 75],
      dtype=int32)

In [13]:
b

array([[39, 62, 54, 61],
       [19, 60, 29, 66],
       [83,  2, 39, 11],
       [70, 44, 67,  6],
       [37, 54, 68, 90],
       [45, 62, 47, 14]], dtype=int32)

In [14]:
np.flip(b,axis=1)

array([[61, 54, 62, 39],
       [66, 29, 60, 19],
       [11, 39,  2, 83],
       [ 6, 67, 44, 70],
       [90, 68, 54, 37],
       [14, 47, 62, 45]], dtype=int32)

In [15]:
np.flip(b,axis=0)

array([[45, 62, 47, 14],
       [37, 54, 68, 90],
       [70, 44, 67,  6],
       [83,  2, 39, 11],
       [19, 60, 29, 66],
       [39, 62, 54, 61]], dtype=int32)

#### **Delete**
- The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [16]:
a

array([75, 53, 36, 33, 44, 21, 88, 95, 19, 93, 83, 85, 71, 89, 29],
      dtype=int32)

In [17]:
np.delete(a,0)

array([53, 36, 33, 44, 21, 88, 95, 19, 93, 83, 85, 71, 89, 29],
      dtype=int32)

In [18]:
np.delete(a,[1,3,5])    # Deleted 1,3,5 index items

array([75, 36, 44, 88, 95, 19, 93, 83, 85, 71, 89, 29], dtype=int32)

In [19]:
b

array([[39, 62, 54, 61],
       [19, 60, 29, 66],
       [83,  2, 39, 11],
       [70, 44, 67,  6],
       [37, 54, 68, 90],
       [45, 62, 47, 14]], dtype=int32)

In [24]:
np.delete(b,0)

array([62, 54, 61, 19, 60, 29, 66, 83,  2, 39, 11, 70, 44, 67,  6, 37, 54,
       68, 90, 45, 62, 47, 14], dtype=int32)

In [25]:
np.delete(b,[0,4])

array([62, 54, 61, 60, 29, 66, 83,  2, 39, 11, 70, 44, 67,  6, 37, 54, 68,
       90, 45, 62, 47, 14], dtype=int32)

#### **Array Manipulation**
You can reshape arrays using np.reshape(), flatten them using np.flatten() or np.ravel(), and transpose them using np.transpose() or array attributes. 
Transpose converts rows into columns and columns into rows.

In [26]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
np.transpose(x)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [29]:
x.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [30]:
arr = np.array([[1,2,3], [4,5,6]])
transposed_arr = np.transpose(arr)
arr,transposed_arr

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

#### **Ravel**
Converting any dimensions into 1D 

In [31]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
y = np.arange(0,8).reshape(2,2,2)
y

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
np.ravel(y)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [35]:
arr = np.array([[1,2,3], [4,5,6]])
flattened_arr = arr.flatten()
flattened_arr

array([1, 2, 3, 4, 5, 6])

In [36]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
y.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

#### **Inverse of Array**

In [39]:
# To invert (or find the inverse of) a NumPy array, you can use the numpy.linalg.inv()

# Create a square matrix (2x2 for example)
matrix = np.array([[3,6],
                   [9,12]])

# Calculate the inverse of
inverse_matrix = np.linalg.inv(matrix)

# Print the original and inverse matrix
print("Original Matrix:")
print(matrix)

print("\nInverse Matrix:")
print(inverse_matrix)

Original Matrix:
[[ 3  6]
 [ 9 12]]

Inverse Matrix:
[[-0.66666667  0.33333333]
 [ 0.5        -0.16666667]]


#### **Array Concatenation**
You can combine arrays using functions like np.concatenate(), np.vstack(), and np.hstack().

In [40]:
arr = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[5,6,4], [5,6,1]])
print(arr)
print(arr2)
concat = np.concatenate((arr, arr2), axis = 0)
concat

[[1 2 3]
 [4 5 6]]
[[5 6 4]
 [5 6 1]]


array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 4],
       [5, 6, 1]])

In [5]:
arr = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[5,6,4], [5,6,1]])
print(arr)
print(arr2)
concat = np.concatenate((arr, arr2), axis = 1)
concat

[[1 2 3]
 [4 5 6]]
[[5 6 4]
 [5 6 1]]


array([[1, 2, 3, 5, 6, 4],
       [4, 5, 6, 5, 6, 1]])

#### **Stacking**
Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be stacked.

In [45]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

vertical_stack = np.vstack(arr1)
horizontal_stack = np.hstack(arr2)
vertical_stack, horizontal_stack

(array([[1],
        [2],
        [3]]),
 array([4, 5, 6]))

In [43]:
c1 = np.arange(12).reshape(3,4)
c2 = np.arange(12,24).reshape(3,4)
print(c1)
print(c2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [47]:
np.hstack((c1, c2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [48]:
np.vstack((c1, c2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### **Splitting**
- It is opposite of stacking
- Splitting arrays can be done with np.split(), np.vsplit(), and np.hsplit().

In [50]:
arr1 = np.array([1,2,3,4,5,6,7,8])
splitting = np.split(arr1, 4)
splitting

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [51]:
np.hsplit(c1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [52]:
np.vsplit(c2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [53]:
a = np.array([[1,2,6], [5,8,9], [5,5,6]])
a

array([[1, 2, 6],
       [5, 8, 9],
       [5, 5, 6]])

In [54]:
np.hsplit(a, 3)

[array([[1],
        [5],
        [5]]),
 array([[2],
        [8],
        [5]]),
 array([[6],
        [9],
        [6]])]

In [55]:
np.vsplit(a,3)

[array([[1, 2, 6]]), array([[5, 8, 9]]), array([[5, 5, 6]])]

#### **Boolean Indexing and Fancy Indexing**:
It allows you to select elements from an array based on a Boolean condition. This allows you to extract only the elements of an array that meets a certain condition, making it easy to perform operations on specific subsets of data.

In [56]:
arr = np.array([10,20,30,40,50])
bool_idx = arr > 25
print(bool_idx)
selected_elements = arr[bool_idx]

indices = np.array([0,2,4])
fancy_selected = arr[indices]

selected_elements, fancy_selected

[False False  True  True  True]


(array([30, 40, 50]), array([10, 30, 50]))

In [57]:
B = np.random.randint(1,100,24).reshape(6,4)
B

array([[86, 25, 23, 39],
       [30, 31, 24, 15],
       [39, 42,  3, 62],
       [56, 24, 31, 27],
       [97, 76, 17, 17],
       [51, 59, 12, 55]], dtype=int32)

In [58]:
B > 50

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True, False,  True]])

In [59]:
B[B > 50]

array([86, 62, 56, 97, 76, 51, 59, 55], dtype=int32)

In [60]:
B % 2 == 0

array([[ True, False, False, False],
       [ True, False,  True, False],
       [False,  True, False,  True],
       [ True,  True, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [62]:
B[B % 2 == 0]   # Find out even numbers 

array([86, 30, 24, 42, 62, 56, 24, 76, 12], dtype=int32)

In [64]:
# Find all numbers greater than 50 and are even
B[(B > 50) & (B % 2 == 0)]

array([86, 62, 56, 76], dtype=int32)

In [65]:
B[~(B % 7 == 0)]  # '~' not

array([86, 25, 23, 39, 30, 31, 24, 15, 39,  3, 62, 24, 31, 27, 97, 76, 17,
       17, 51, 59, 12, 55], dtype=int32)

In [66]:
B[np.array([0,2,4])]

array([[86, 25, 23, 39],
       [39, 42,  3, 62],
       [97, 76, 17, 17]], dtype=int32)

#### **Array Broadcasting**
Broadcasting allows you to perform operations between arrays of different shapes.
NumPy automatically handles shape compatibility be replicating values along dimensions as needed. This is particularly useful for operations that involve arrays of different shapes.

In [ ]:
# Scalar and Array Broadcasting
scalar = 5
array = np.array([1,2,3,4,5,6])


#### **File I/O with NumPy**
You can save and load arrays to or from files using np.save() and np.load().

In [67]:
arr = np.array([[1,2,3], [4,5,6]])
np.save("my_array.npy", arr)

In [68]:
loaded_arr = np.load("my_array.npy")
loaded_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
loaded_arr[loaded_arr % 2 == 0]

array([2, 4, 6])